slackapi/deno-slack-sdk

docs/types.md
src/manifest_test.ts
src/parameters/parameter-variable_test.ts
src/types/mod.ts
src/types/types.ts

Move the type `id` into the `definition` to match the change to `DefineFunction`

Move id arg to def in DefineType

---

src/functions/functions_test.ts
src/functions/types.ts
src/manifest_test.ts
src/parameters/mod.ts
src/parameters/parameter-variable_test.ts
src/parameters/types.ts
src/schema/schema_types.ts
src/schema/slack/schema_types.ts
src/types/mod.ts

Removing types that are not going to be supported at re-ignite.
Since the majority of these types will be re-added, I've commented them out for the time being.
For re-ignite we are only supporting the following types, based on [this doc](https://corp.quip.com/XaUHABd6ZPUp/Reduce-function-input-type-support-to-match-Block-Kit-Decision):
- `string`
- `boolean`
- `user`
- `channel`
- `array` of
- `string` as an `enum`
- `user`
- `channel

Change the supported types for reignite

---

docs/functions.md
docs/manifest.md
src/manifest.ts
src/manifest_test.ts
src/types.ts

Removing `runtime` from the manifest as it's no longer used by the builder as of https://github.com/slackapi/deno-slack-builder/pull/15

Remove runtime param from manifest

---

docs/functions.md
src/functions/types.ts
src/types.ts

Adjusting the `FunctionHandler` type to provide some typing for functions at reignite.
At reignite, this will be used in our template function definition file like
```ts
import type { FunctionHandler } from "deno-slack-sdk/types.ts";
// deno-lint-ignore no-explicit-any
const reverse: FunctionHandler<any, any> = async (
{ inputs, env },
) => {
const reverseString = inputs.stringToReverse.split("").reverse().join("");
return await {
outputs: { reverseString },
};
};
export default reverse;
```
Out of the box, the dev will get typing on all parts of the function other than their inputs and outputs. They will also be able to type the function themselves if they want to maintain them.
After type generation is in place, this will look like
```ts
// generated-types/reverse.ts file
import type { …
```

Add generic typing for functions

---

src/datastore/mod.ts
src/datastore/types.ts
src/manifest.ts
src/manifest_test.ts
src/types.ts

Adding some logic to
- automatically register types used by datastores
- automatically append datastore scopes to bot scopes

Add type registration to datastores and auto-append scopes

---

src/manifest_test.ts

Looks like some `runtime` remnants snuck in as part of the [datastore PR](https://github.com/slackapi/deno-slack-sdk/commit/aa5aeaf29f51be1ce3515d6ec94c7e7a93528754)

Fixing tests

---

src/dev_deps.ts
src/functions/functions_test.ts
src/manifest_test.ts
src/parameters/parameter-variable_test.ts
src/parameters/with-untyped-object-proxy_test.ts

It is a good practice to centralise Deno dependencies within `deps.ts` and `dev_deps.ts` files.
See https://deno.land/manual/examples/manage_dependencies
---
Related to https://github.com/slackapi/deno-slack-api/pull/6 and https://github.com/slackapi/deno-slack-builder/pull/14

Use deps.ts and dev_deps.ts.

---

src/functions/function_tester.ts
src/functions/function_tester_test.ts
src/mod.ts

This creates a new top level export of `SlackFunctionTester` that can be used to ease writing tests for Slack Functions. Consuming it would like like the following when writing a test for  a function in your project:
```ts
// Can call this anywhere in your test file
const { createContext } = SlackFunctionTester("reverse_string");
```
And then in your tests where you need to pass arguments into your function...
```ts
const { outputs } = await ReverseString(createContext({ inputs }));
A full test would like like the following:
```ts
import { assertEquals } from "https://deno.land/std@0.99.0/testing/asserts.ts";
import ReverseString from "./reverse.ts";
import { SlackFunctionTester } from "deno-slack-sdk/mod.ts";
const { createContext } = SlackFunctionTester("reverse_string"); …

adding a SlackFunctionTester to help with writing function tests

---

src/functions/types.ts

JIRA TIcket: [HERMES-2473](https://jira.tinyspeck.com/browse/HERMES-2473)
If we catch an error in the function execution, we should be able to return the error without needing to set any outputs.
Right now if we return from a caught error we need to provide outputs
```ts
try {
throw new Error();
} catch (e) {
return await {
error: e,
outputs: {}
};
}
```
but this isn't required by our BE so we shouldn't require `outputs` in the response if `error` is provided
```ts
```ts
try {
throw new Error();
} catch (e) {
return await {
error: e,
};
}
```

[HERMES-2473] Function return args no longer require an output if there is an error

---

src/functions/functions_test.ts
src/functions/types.ts
src/parameters/mod.ts

Moving the required field beneath the properties
There was confusion about a TS error around a required field that wasn't actually a parameter yet. We haven't figured out the right way to give specific error messaging for this kind of situation with our types, but it makes more sense to define the properties that are available before we say which are required.
Convo: https://slack-pde.slack.com/archives/C03BS52QLPJ/p1649958372816539
Relevant PR: https://github.com/slackapi/deno-reverse-string/pull/24

Move the required field under the properties

---

src/functions/types.ts

This goes along with the following PR for the runtime: https://github.com/slackapi/deno-slack-runtime/pull/12
After that runtime is released, we can release this type change to allow sync or async function handlers. This will allow someone to write a function handler w/o the `async` keyword if they don't need it. So instead of:
```ts
const reverse: FunctionHandler<any, any> = async ({ inputs, env }) => {
const reverseString = inputs.stringToReverse.split("").reverse().join("");
return await {
outputs: { reverseString },
};
};
```
It could just be:
```ts
const reverse: FunctionHandler<any, any> = ({ inputs, env }) => {
const reverseString = inputs.stringToReverse.split("").reverse().join("");
return {
outputs: { reverseString },
};
};
```

Support async and sync function handlers

---

src/datastore/mod.ts
src/datastore/types.ts

Making the `definition` property of a Datastore instance public (so we can reference it [for typed apis](https://github.com/slackapi/deno-slack-api/pull/9)). Also added generics for `name` and `primary_key` to support stricter typing on apis using the definitions as generics.
This should change anything with how a datastore is created/referenced in the SDK alone, but will allow testing a new PR to the api client w/ typed datastore methods.
https://github.com/slackapi/deno-slack-api/pull/9

Updating datastore types with generics and making definition public

---

.gitignore
deno.jsonc
src/dev_deps.ts
src/functions/base_function_handler_type_test.ts
src/functions/function_tester.ts
src/functions/function_tester_test.ts
src/functions/slack_function_handler_type_test.ts
src/functions/types.ts
src/parameters/mod.ts
src/types.ts

This PR aims to provide a low-effort solution for developers to write typed function handlers.
```ts
// Define a function in `manifest.ts`
export const ReverseFunction = DefineFunction({...});
// then in your function handler file...
import type { SlackFunctionHandler } from "deno-slack-sdk/types.ts";
// in your function source file, import it as a type to reference in the handler type
import type {ReverseFunction } from "../manifest.ts";
// use the new SlackFunctionHandler type w/ a typeof against the function definition property
const ReverseString: SlackFunctionHandler<typeof ReverseFunction.definition> = (
{ inputs },
) => {
//...
return {
outputs: {
//...
},
};
};
```
This will keep the function typed so it matches the definition without the need to duplicate or generate any static …

Making typed function handlers easier

---

src/functions/mod.ts
src/functions/types.ts
src/manifest.ts
src/mod.ts
src/parameters/mod.ts
src/types.ts
src/workflows/mod.ts
src/workflows/types.ts
src/workflows/workflow-step.ts
src/workflows/workflows_test.ts

This exports a `DefineWorkflow()` from the main `mod.ts` file. It will create a workflow definition to be inserted into the `workflows` array in the manifest.
_Example of workflow being defined_
```ts
const ReacjiChannelerWorkflow = DefineWorkflow({
callback_id: "reacji_channeler",
title: "Reacji Channeler",
input_parameters: {
properties: {
forward_channel: {
type: Schema.slack.types.channel_id,
},
message_channel: {
type: Schema.slack.types.channel_id,
},
message_ts: {
type: Schema.types.string,
},
},
required: ["forward_channel", "message_channel", "message_ts"],
},
});
```
A workflow isn't very fun (or valid) without some steps. Steps can be added by one of two ways:
This is what you have after calling `DefineFunction()`
```ts
const GetMessagePermalink = DefineFunction(...);
const …
```

Workflow Definition support

---

src/manifest.ts
src/manifest_test.ts
src/types/mod.ts
src/types/types.ts

Make sure `callback_id` doesn't make it to the manifest
Right now if we try to use a type and deploy it, we'll get an error from the API endpoint that `callback_id` isn't a valid field for types. We need to make sure that `callback_id` is dropped before we export the manifest, which we now do by using an `export` method on the Custom Type.

Remove callback_id from the type we export to the manifest

---

docs/manifest.md
docs/workflows.md

Adding a `workflows.md` doc file that explains the basics of how a workflow can be defined. At this point, it's missing a callout to how you would setup a trigger to call a workflow, but that's pending that functionality landing still. In the vein of having a start to the workflows docs, and something we could point those that are interested in just defining workflows in code, I wanted to put this together.

Adding a workflows doc

---

src/functions/types.ts
src/parameters/mod.ts

Added a PendingFunctionReturn type to allow functions to return the {completed: false} state. Unsure whether we should be allowing output along with completed: false in the future

added a Pending state to the function output type

---

src/functions/functions_test.ts
src/functions/types.ts
src/parameters/types.ts
src/schema/schema_types.ts
src/schema/slack/schema_types.ts

Add type support for `integer`, `number`, `usergroup_id`, `timestamp`, and `blocks`
Reintroducing support for types that aren't supported by input fields.
I'd recommend doing this somewhere with auto-generated shortcuts still enabled for every function, and then using these various types.

Add type support for integer, number, usergroup, timestamp, and blocks

---

docs/types.md
src/datastore/datastore_test.ts
src/functions/base_function_handler_type_test.ts
src/functions/slack_function_handler_type_test.ts
src/functions/types.ts
src/manifest_test.ts
src/parameters/mod.ts
src/parameters/parameter-variable_test.ts
src/parameters/types.ts
src/schema/schema_types.ts
src/types/mod.ts
src/workflows/workflows_test.ts

Reintroducing support for the `object` type
This is built on top of the general `neil-readd-types` branch. It reintroduces support for:
- The type in `SchemaTypes`
- Using `object` as a parameter
- Object property workflow step output access
- Object property runtime access
- Unsupported objects (no defined `properties`)
- Manifest auto-registration for `types` and `datastores`
While verifying I identified two pre-existing bugs that I entered tickets for:
- [Deno SDK — Typeahead does not work for an Object parameter's `required` field](https://jira.tinyspeck.com/browse/HERMES-3054)
- [Deno Client — Datastore attributes of type object do not give typeahead](https://jira.tinyspeck.com/browse/HERMES-3055)

Adding support for the Object type again

---

src/manifest.ts
src/manifest_test.ts
src/types.ts

Adding a support to enable message tab in the app profile.

Support for read_only_message_tab

---

src/dev_deps.ts
src/functions/routers/action_router.ts
src/functions/routers/action_router_test.ts
src/functions/routers/mod.ts
src/functions/routers/types.ts
src/functions/tester/mod.ts
src/functions/tester/types.ts
src/functions/types.ts
src/mod.ts
src/types.ts

Mostly following the template experimented with here: https://corp.quip.com/FF6hAO3C4UbL/Function-Interactivity-Examples
Pair this up with the PR on internal GitHub for the app consuming this: https://slack-github.com/bharris/interactive-approval/pull/1
Also loosely based on[ @selfcontained's `bradh-fn-interactivity-handlers-duex` branch of deno-slack-runtime](https://github.com/slackapi/deno-slack-runtime/tree/bradh-fn-interactivity-handlers-duex).

First pass at Action Handlers / a router for actions

---

src/functions/routers/action_router.ts

These type errors show up when trying to build the SDK. Errors are related to referencing private `this` in the return type of a public method in an exported class.

Resolves type errors

---

src/functions/types.ts
src/parameters/mod.ts
src/schema/slack/schema_types.ts
src/workflows/workflows_test.ts

Adding crude support for the new `user_context` and `interactivity` Slack types
Adding `user_context` and `interactivity` to our list of `SlackTypes`.
Set `user_context` and `interactivity` as the types for function and workflow input/output parameters and verify that they're appropriately treated in the output of `hermes manifest`.

Initial support for `user_context` and `interactivity` types

---

src/functions/routers/action_router.ts
src/functions/routers/action_router_test.ts
src/functions/routers/block_actions_types.ts
src/functions/routers/types.ts

This adds a little bit more typing for the `body` of the BlockActionsRouter handlers. I've added the new `interactivity` portion of the payload, and then flushed out some of the other more common and simple properties for now, such as `user` and `team`, as well as other portions of the payload. Ideally we can come up with a strategy to centralize these payload types to share across our libraries.

Adding some typing for block_actions body

---

src/manifest/manifest_test.ts
src/manifest/mod.ts
src/manifest/types.ts

Adds org_deploy_enabled: true for run on slack apps.
* RoS App devs do not need to set this value, at the moment they also should not be able to set this value either, since there's no option but `true`.
* Remote App devs retain the ability to set this value via manifest.settings.org_deploy_enabled
https://user-images.githubusercontent.com/55667998/181834459-66048168-b96f-468d-a253-2c45f40d2bea.mov

Adds RoS App Settings defaults: org_deploy_enabled

---

src/functions/slack_function_handler_type_test.ts
src/functions/types.ts
src/parameters/mod.ts
src/parameters/types.ts
src/schema/slack/schema_types.ts
src/schema/slack/types/custom/interactivity.ts
src/schema/slack/types/custom/mod.ts
src/schema/slack/types/custom/user_context.ts
src/schema/slack/types/mod.ts
src/test_utils.ts

This uses Custom Slack Types instead of the hardcoded checks!
Using `user_context` and `interactivity` as function input/output parameters within a workflow should continue to work and not change

Use Custom Types for `user_context` and `interactivity` types

---

src/manifest/manifest_test.ts
src/manifest/mod.ts

`Manifest` now outputs `token_management_enabled: false` by default for all run on slack apps (aka where function_runtime is set as `slack`.
* `tokenManagementEnabled` property does not appear in typeahead. In future, all run on slacks apps created should default to false in the backend so I figured it'd be better to keep this property out of sight. 
https://user-images.githubusercontent.com/55667998/181822386-6986a48f-37a7-4584-ab59-c5ac1ab487df.mov
* Manifest outputs the proper property
https://user-images.githubusercontent.com/55667998/181822461-28baa01e-2292-4441-8157-ea2991b92444.mov
* This does not impact remote / Bolt apps. tokenManagementFalse remains an [optional property f](https://github.com/slackapi/deno-slack-sdk/blob/5c61e062a0da51a30ab6ba0ce0378a31f93a8b0d/src/manifest/types …

Default tokenManagementEnabled to false for runOnSlack apps

---

src/workflows/mod.ts

Changed the definition field in WorkflowDefinition to a public variable.

changed Workflow definition to public

---

src/functions/types.ts
src/schema/slack/types/mod.ts

Adds `slack#/types/date` to the `Schema`. At runtime it's a string (it's format is `YYYY-MM-DD`).
To test this you can use an Open Form step and add a field of `Schema.slack.types.date` - it should render a date-picker like in the screenshot.
You can embed that output into a Send a message step's `message` input and you should see the date string you selected, like so:

adding slack#/types/date

---

src/functions/interactivity/action_router_test.ts
src/functions/interactivity/view_router_test.ts
src/functions/tester/mod.ts
src/functions/types.ts

`team_id` should now be available on all dispatched events to userland functions via runtime.

Exposing team_id to FunctionContext

---

src/functions/interactivity/block_actions_types.ts
src/functions/slack_function_handler_type_test.ts
src/functions/types.ts
src/parameters/mod.ts
src/parameters/parameter-variable_test.ts
src/parameters/types.ts

The backend defaults `additionalProperties` on parameters of the `object` type to true, so this PR inverts the check to see if they are explicitly setting `additionalProperties` to false.
1. Create an `object` parameter as a function input or output
2. Verify that at both workflow authoring time and at runtime, you're able to access unexpected properties.
3. Change the object parameters you created to set `additionalProperties: false`
4. Notice that your access of unexpected properties now results in errors.
```ts
anObject: {
type: Schema.types.object,
properties: {
test: { type: Schema.types.string },
},
additionalProperties: false,
},
```

Check for additionalProperties to be set to false

---

src/manifest/manifest_test.ts
src/providers/oauth2/types.ts

Jira ticket: https://jira.tinyspeck.com/browse/PAX-11407
- The environment variable name `client_secret_env_key` became redundant and the internal 3p auth users are supposed to be using a new subcommand  `add-secret` instead of the .env variable
- Therefore we are removing the field `client_secret_env_key` from the SDK object
- The webapp should be okay to accept the oauth2 object now if this field is optional there (TODO check)
- There will be a CLI change as well to get rid of this field completely. [PR](https://github.com/slackapi/slack-cli/pull/682)
- This PR can be merged after the new `add-secret` subcommand is available to the end user.
How to test:
- This needs to be tested after the `client_secret_env_key` field becomes optional in the …

[PAX-11407] [merge after 8/25] removing client_secret_env_key from manifest

---

src/functions/functions_test.ts
src/parameters/types.ts

[PSA-2507](https://jira.tinyspeck.com/browse/PSA-2507) - For function parameters, we are introducing a new attribute `hint` . This can be used to display warnings or any text that is in addition to title, description and it will be displayed under the input field.
Refer this  [Tech spec](https://corp.quip.com/yTZNAw5OUNKv/Tech-Spec-Add-a-new-optional-property-hint-to-function-parameters) for the details.
1. Create a new Hermes app ( reverse string template ), Add `hint` attribute to `Reverse string` function param. 
```
export const ReverseFunction = DefineFunction({
callback_id: "reverse_hint",
title: "Reverse hint",
description: "Takes a string and reverses it",
source_file: "functions/reverse.ts",
input_parameters: {
properties: {
stringToReverse: {
type: Schema.types.string, …
```

PSA-2507 : Add new attribute hint to Function parameters

---

src/workflows/mod.ts
src/workflows/types.ts

This makes it so that we respect the value passed into `callback_id`, rather than treating it as any old `string`. This is necessary for us to key off of `callback_id` to know what should be passed into a trigger's `workflow` parameter in the API.
There is no functional difference here, but you could test making and deploying workflows for a sanity check.

Make the workflow callback_id generic

---

src/manifest/manifest_test.ts
src/manifest/mod.ts
src/manifest/types.ts

Removes `tokenManagementEnabled` top level property from the Manifest definition, and sets corresponding token_management_enabled property in the Manifest Schema as true for runOnSlack: false apps. 
Samples with `tokenManagementEnabled` field should also be updated.

Default token_management_enabled:true for runOnSlack:false apps

---

src/events/mod.ts
src/events/types.ts
src/events/types_test.ts
src/manifest/manifest_schema.ts
src/manifest/manifest_test.ts
src/manifest/mod.ts
src/manifest/types.ts
src/mod.ts

This PR adds support for defining events on the App Manifest.
When an app uses `chat.postMessage` from inside a function, they can optionally pass a `metadata` object. That `metadata` object will have an `event_type` and an `event_payload`. If the `event_type` matches one of the keys from the app manifest's `events` object, the `event_payload` needs to match the metadata schema.
* If there are required properties that are missing, the message will still successfully post but the metadata will be dropped and the response will include a `warning` and a `response_metadata` object.
* There are plans to eventually support a "strict mode" that will fail the `postMessage` call entirely, but that's not currently supported.
* If there are additional properties that are not defined in the manifest, …

Add support for custom metadata events

---

src/functions/types.ts
src/manifest/manifest_test.ts
src/types.ts
src/types/mod.ts
src/types/types.ts
src/types/types_test.ts

This removes 2 deprecated items:
* Top level `FunctionHandler` export that was replaced with `SlackFunctionHandler` type.
* CustomType definitions support for `callback_id` that was replaced with `name`.

Remove some deprecated items

---

src/functions/tester/function_tester_test.ts
src/functions/types.ts

This fixes a bug in the `SlackFunctionType` to use a union instead of the incorrect usage of a function w/ a return arg of type  `SlackFunctionHandler`. This causes a bug when trying to import and use the export in a unit test w/ the `SlackFunctionTester`.

fixing SlackFunctionType union

---

src/manifest/manifest_schema.ts
src/manifest/mod.ts
src/manifest/types.ts

Ensures `home_tab_enabled` doesn't show up during RunOnSlack app manifest authoring as the related app_home_opened event isn't supported at the moment for ROSI apps.

Remove home_tab_enabled for runOnSlack apps

---

src/events/mod.ts
src/parameters/mod.ts
src/parameters/types.ts
src/types/mod.ts

This reverts commit 895e3d9484eeb720a6e6d118bc13960b6649b332.
Reverts this "fix"
This commit introduced a bug where two workflows with parameters being used will result in an infinite loop error. Verify that using two workflows with parameters will not lead to an error.
Note that this reintroduces the issue where Parameters aren't properly typed based on the value provided to the `type` property.

Revert "Fix parameter typing based on the discriminate union (#96)"

---

src/manifest/manifest_test.ts

Adds a test to ensure there are no errors when passing two workflows with input parameters into `Manifest()`

Adding a test for multiple workflows passed into Manifest()

---

.github/CODEOWNERS

Add developer education team as codeowner of docs dir

Add developer education team as codeowner of docs dir

---

src/functions/interactivity/block_actions_types.ts
src/functions/types.ts

Adding typing to Block Kit action handler's `body.message` property. Tried to document where I was able to find resources on the subject. Sort of a random conglomeration; might not be exactly correct based on the various contexts that the shape of these payloads tend to change: enterprise grid vs. non-grid workspace, message vs. view container for block kit, to name a few that I know of.

HERMES-3573: Add type to `body.message` Block Action handler argument

---

.github/workflows/npm.yml
build_npm.ts

@fil discovered that - `build_npm.ts` which uses `dnt` package to build deno modules for npm distribution - was failing due to some recent changes that added deno-slack-api as an overall project dependency.
This PR resolves that issue by adding a polyfill for that dependency. 
Related to [this PR](https://github.com/slackapi/deno-slack-sdk/pull/106) which adds an extra check on PRs to main to run the build.

[HERMES-3843] Shim deno fetch api for npm build

---

src/functions/interactivity/action_router_test.ts
src/functions/interactivity/types.ts
src/functions/interactivity/view_router_test.ts
src/functions/tester/types.ts
src/functions/types.ts

This pull request resolves the compilation errors due to Deno 1.26 breaking changes. Once the changes in this PR land, the CI builds for my PR https://github.com/slackapi/deno-slack-sdk/pull/109 should pass.

Update type parameters to be compatible with Deno 1.26 breaking changes

---

docs/functions-action-handlers.md
docs/functions-view-handlers.md
docs/functions.md

Also: handler-registration methods that chain off the SlackFunction instead of documenting the old Router constructs.
I will send a similar PR to webapp to update the docs on api.slack.com/future as well shortly.

Updating interactivity docs for block actions and view events to use the SlackFunction construct

---

docs/functions.md
src/functions/enrich-context_test.ts
src/functions/interactivity/action_router_test.ts
src/functions/interactivity/view_router_test.ts
src/functions/tester/mod.ts
src/functions/types.ts

Relies on the work in https://github.com/slackapi/deno-slack-runtime/pull/38.
Exposes an `enterprise_id` property to all handlers.

Expose enterprise_id to userland handlers.

---

src/functions/interactivity/block_actions_types.ts

Mark the `response_url` field in BlockActionBody deprecated, since it will be removed in the next release.

HERMES-4039: mark response_url deprecated

---

src/datastore/datastore_test.ts
src/events/types_test.ts
src/functions/functions_test.ts
src/workflows/workflows_test.ts

This pull request adds a few assertions, which mainly clarify how id properties are set as the results of Define utility calls, in unit tests. No changes to the main code side.

Add assertions on definition properties in tests

---

src/functions/interactivity/block_actions_types.ts

Reverts slackapi/deno-slack-sdk#115. The team will keep supporting this for now.

Revert "HERMES-4039: mark response_url deprecated"

---

src/deps.ts

Bump the SlackApi version to the current

Bump the SlackApi version to the current

---

.github/maintainers_guide.md

Adds some helpful tips for incorporating local changes into a sample for manual verification

Add manual testing instructs to maintainers guide

---

src/parameters/types.ts

Adds `format` property to StringParameterDefinition type.
You can easily clone down this app and follow these [instructions](https://github.com/srajiang/test-format-string/blob/7926cb0d803dc930350d72812b1dde49cb1a485e/functions/greeting_function.ts#L24-L32) to test out the addition. 
Errors you should see: 
1. Manifest validation error when value for `format` does not match either "email" or "url". For example `uri` should both cause a manifest validation error. 
2. Parameter validation error when the value does not conform to the specified format

Add format property to StringParameterDefinition type

---

src/functions/types.ts
src/schema/slack/types/custom/custom_slack_types_test.ts
src/schema/slack/types/custom/message_context.ts
src/schema/slack/types/custom/mod.ts
src/schema/slack/types/mod.ts
tests/integration/functions/function_handler_test.ts

Added `message_ts` to `SlackPrimitiveTypes` and `message_context` to `CustomSlackTypes`. 
Created new `MessageContextType` as the new Custom Type.
Requirements can be found below: 
- `message_ts` should be added to SlackPrimitiveTypes as a simple string
- `message_context` should be added to CustomSlackTypes as a Custom Type definition of an object with properties that can be found here:
https://corp.quip.com/9T6nAE8mUHxn/Reply-In-Thread-Builtin-Function#temp:C:VKKb19fca4ebf8c44c2b9b6732bc

Added message_ts and message_context

---

.github/PULL_REQUEST_TEMPLATE.md

Fix the link in the PR template
1. Try to click the link below to the Contributing Guidelines in this PR
2. Fail

Fix the link to the Contributing Guidelines in the PR template

---

src/functions/interactivity/block_actions_types.ts
src/functions/interactivity/view_types.ts

Reverts https://github.com/slackapi/deno-slack-sdk/pull/117/ again, effectively putting the deprecation notice back.
Also deprecates `response_urls` which is related.

Add deprecation notice to response_url and response_urls

---

.github/maintainers_guide.md
.vscode/settings.json
deno.jsonc

Original request suggests moving to `.editorconfig` to set formatting and linting rules. After doing some research on [Deno development environments](https://deno.land/manual/getting_started/setup_your_environment), I created this PR in which all the formatting and linting rules are defined in the `deno.jsonc` file. 
Deno supports multiple IDE's with plugins that allow to set the `deno.json` file as the configuration file for formatting and linting. I've updated the vscode `settings.json` file to use this configuration file.
Users of other IDEs will be able to follow the steps in the `maintainers_guide` to set up their IDE with the proper plugin and reference the `deno.jsonc` file.

Deno editor configuration

---

deno.jsonc

Small tweak to the coverage task, I think the output is much nicer and it also gives you a project-wide total (which the built-in deno CLI `deno coverage` tool does not):

Integrate a better CLI utility for generating code coverage reports.

---

src/workflows/types.ts

Found this instance where we're naming a generic variable `Parameters` which is a utility type.

Dont use Parameters as a generic name because it's a utility

---

.github/maintainers_guide.md

This PR adds a few instructions for testing the changes of a local SDK in a sample app.

Add documentation for sample app testing with a local SDK

---

src/deps.ts

This PR simply bumps the deno-slack-api version to the latest

Bump the deno-slack-api version

---

src/datastore/types.ts
src/parameters/definition_types.ts
src/schema/schema_types.ts
src/schema/slack/types/mod.ts
src/type_utils.ts

Show users via typeahead what values are accepted in the `type` field for functions and datastores while still allowing any other string value to be passed
[h/t to Matt Pocock](https://twitter.com/mattpocockuk/status/1671908303918473217?cxt=HHwWgoCxgdHv57MuAAAA)
https://github.com/slackapi/deno-slack-sdk/assets/20157895/043cd7e3-234d-4fa3-aa4b-8b89c3e8803b

Provide typeahead for the `type` property

---

src/manifest/manifest_test.ts
src/providers/oauth2/types.ts

To support more connectors, 3p auth manifest config requires some more new SDK fields
This PR is to add a new field that helps the connector team unblock creating some more connectors.
`token_url_config : { use_basic_authentication_scheme_scheme : boolean}` to support providers that use this.
More discussions can be found in our slack instance.
closing [this old PR](https://github.com/slackapi/deno-slack-sdk/pull/198) for this.
Please do not merge it until the web app changes are merged! Thanks!

adding use basic auth scheme config

---

src/providers/oauth2/oauth2_test.ts
src/providers/oauth2/types.ts

The new field added in the previous PR had a typo.
To support more connectors, 3p auth manifest config requires some more new SDK fields
This PR is to add a new field that helps the connector team unblock creating some more connectors.
`token_url_config : { use_basic_auth_scheme_scheme : boolean}` to support providers that use this.
More discussions can be found in our slack instance.
Please do not merge it until the web app changes are merged! Thanks!

fixing the property

---

.github/workflows/npm-publish.yml

`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
- I think the next publish action should successfully go through?
I have scanned all repositories owned by `slackapi` (thanks to [gh-clone-org extension](https://github.com/matt-bartel/gh-clone-org) from [this issue](https://github.com/cli/cli/issues/2450#issuecomment-978093661)) and there is only one instance of usage. 
It's `set-output` on …

Use GITHUB_OUTPUT envvar instead of set-output command as the latter is deprecated

---

src/datastore/mod.ts
src/datastore/types.ts
src/manifest/manifest_schema.ts

This PR adds support for the AWS DynamoDB TimeToLive feature on Slack app datastores. This feature allows developers to identify an attribute in their datastore schema which serves as an expiration timestamp. In the background, DynamoDB will check for items which have this attribute populated with an epoch timestamp < now and delete them from the DynamoDB table. 
To enable the feature, add `time_to_live_attribute` in the `DefineDatastore` function arguments and specify an attribute from the `attributes` map which has type `Schema.slack.types.timestamp`.
Example:
```
const SongDatastore = DefineDatastore({
name: SONG_DATASTORE,
primary_key: "id",
time_to_live_attribute: "song_played_date",
attributes: {
id: {
type: Schema.types.string,
},
...
song_played_date: {
type: …
```

Add time_to_live_attribute to datastore module

---

.gitignore
src/deps.ts

Upgrading deno-slack-api to v2.4.0 (support for `all_resources` event triggers)

---

src/README.md

The sentence:
> Contributions are more **then** welcome.
Should read:
> Contributions are more **than** welcome.
N/A.
N/A.

Fix typo in README.md

---

src/deps.ts

Fixes an issue with the API client proxying calls to `then`; https://github.com/slackapi/deno-slack-api/releases/tag/2.7.1

Bump deno_slack_api to 2.7.1

---

deno.jsonc
src/deps.ts

This PR bumps the deno-slack-sdk version to the latest
N/A
N/A

chore: bump the api dependency version

---

src/functions/types.ts
src/schema/slack/types/mod.ts

This PR aims to add a new hidden type `slack#/types/salesforce_record_id`
This type behaves as a string, similar to other `id` types like `user_is`, `canvas_id` etc ...
This aims to unblock https://github.com/slackapi/deno-slack-hub/pull/66

feat: add salesforce record id type

---

deno.jsonc

This PR configures the project to allow [non import prefixes](https://docs.deno.com/lint/rules/no-import-prefix/), non import prefixes are critical to this project
The CI is passing
In the future we may want to import dependencies through the `deno.jsonc` file similar to how our [templates](https://github.com/slack-samples/deno-starter-template/blob/main/deno.jsonc) do. We will need to investigate if this is a breaking change.

fix: allow non import prefix
