- docs/manifest.md
This PR fix the markdown highlighting.
> Fix markdown highlighting.

- src/datastore/datastore_test.ts
- src/dev_deps.ts
- src/functions/functions_test.ts
- src/manifest_test.ts
- src/parameters/parameter-variable_test.ts
- src/parameters/with-untyped-object-proxy_test.ts
This PR enforces stricter assertions, as very often comparison are done between primitives
> Enforce stricter assertions

- .github/workflows/deno.yml
This PR upgrades the actions versions.
> Upgrade actions.

- README.md
- docs/datastores.md
- docs/functions.md
- docs/manifest.md
- docs/types.md
Update pass on docs.
- Ran `deno fmt` on doc files
- Added `docs/datastores.md`
- Updated `functions`, `types`, and `manifest` docs
> Add datastore doc and update pass on other docs as well

- .github/CODEOWNERS
Add codeowners file referencing our [new slackapi/HDX team](https://github.com/orgs/slackapi/teams/hdx)
> Add basic codeowners file

- docs/workflows.md
Clarifies import statement for `DefineWorkflow` in a code example.
> Clarify import example in workflow doc

- .vscode/settings.json
Remove Deno unstable vscode setting
> Remove Deno unstable from vscode settings

- src/functions/base_function_handler_type_test.ts
- src/functions/slack_function_handler_type_test.ts
- src/functions/types.ts
Added tests to the functionhandler to account for completed: false output and error only output
> added tests to the functionhandler

- src/manifest_test.ts
- src/types/mod.ts
- src/types/types.ts
- src/types/types_test.ts
Add new name property to DefineType definition
> Add new name property to DefineType definition

- docs/types.md
- src/datastore/datastore_test.ts
- src/manifest_test.ts
- src/parameters/parameter-variable_test.ts
- src/types/mod.ts
- src/types/types.ts
Added CustomTypeDefinition type and replaced usage of callback_id with name
> Danielhw deprecated definetype function

- .github/workflows/npm-publish.yml
- .gitignore
- build_npm.ts
This PR was based on a [previous PR.](https://github.com/slackapi/deno-slack-sdk/pull/61) Due to commit history conflicts, created a new branch and moved the changes in the previous PR.
* [ x ] I've read and understood the [Contributing Guidelines](https://github.com/{project_slug}/blob/main/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [ x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
> deno-slack-sdk publish to npm on tag push (new)

- docs/functions-action-handlers.md
- docs/functions.md
Basic introductory docs for how to use action handlers.
Includes a kind of introduction/tutorial at the start, and API reference at the end.
Probably easiest to review using the GitHub markdown-rendered view here: https://github.com/slackapi/deno-slack-sdk/blob/action-handler-docs/docs/functions-action-handlers.md
> First pass at basic action handler tutorial.

- docs/functions-action-handlers.md
- docs/functions-view-handlers.md
- docs/functions.md
My first go at adding documentation for the new view handlers.
> First pass at view handler documentation

- docs/functions.md
Also add , add team_id to list of function context variables.
> Add specific instructions on how to implement a function in docs

- build_npm.ts
Adds min supported engines properties to npm build package.json
> Adds min supported engines properties to npm build package.json

- src/deps.ts
> Bump deno-slack-api version

- .github/maintainers_guide.md
Describe the goal of this PR. Mention any related Issue numbers.
> Clarify setting release version w PR tags

- src/deps.ts
- src/functions/types.ts
Bump the SlackApi version to the current
> Bump the SlackApi version to current

- src/deps.ts
Updating API version to latest
> Update API version to 1.6.0

- src/mod.ts
I forgot to export this bad boi earlier 😢 
But I have come to atone for my shortcomings.
> Export `DefineProperty` on the main `src/mod.ts` file.

- src/manifest/manifest_test.ts
- src/manifest/mod.ts
> Ignore empty array values for manifest's `externalAuthProviders`

- src/functions/interactivity/block_actions_types.ts
- src/functions/interactivity/view_types.ts
- src/types.ts
Removing features that have the `@deprecated` tag
> Remove deprecated features

- src/deps.ts
> Update the API library

- .github/maintainers_guide.md
This PR aims to add a dependency graph that provides a visual representation of the dependencies between repos, this is mainly to help new maintainers
View the graph: https://github.com/slackapi/deno-slack-sdk/blob/add-dependency-graph/.github/maintainers_guide.md#dependency-graph
> Add dependency graph

- build_npm.ts
- src/deps.ts
This PR bump the deno-slack-api version
> Bump api version

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/maintainers_guide.md
- deno.jsonc
This PR aims to improve the contribution guidelines of this project in the goal of increasing external contributions. It improves the issue submission process by adding multiple types of issue templates, improves clarity in the pull request template and cleans up the CONTRIBUTING/maintainers_guide documentation.
Rendered links:
- [CONTRIBUTING.md](https://github.com/slackapi/deno-slack-sdk/blob/improve-contributing-guidelines/.github/CONTRIBUTING.md)
- [maintainers_guide.md](https://github.com/slackapi/deno-slack-sdk/blob/improve-contributing-guidelines/.github/maintainers_guide.md)
- [PULL_REQUEST_TEMPLATE.md](https://github.com/slackapi/deno-slack-sdk/blob/improve-contributing-guidelines/.github/PULL_REQUEST_TEMPLATE.md)
- ISSUE_TEMPLATE
- …
> Improve contributing guidelines

- .github/PULL_REQUEST_TEMPLATE.md
Minor thing: Capitalize testing heading in PR template.
N/A
N/A
> Capitalize testing heading in PR template

- .github/PULL_REQUEST_TEMPLATE.md
> chore: improve pull request template notes

- src/deps.ts
This PR bumps the `deno-slack-api` dependency to the latest version
> fix: bump the api dependency

- docs/datastores.md
This PR updates some syntax and patterns around `datastores` and `functions` to use the latest features from this SDK. 🙏
Using `SlackFunction` might be opinionated so please let me know if this should change!
This matches the latest patterns in [slack-samples/deno-starter-template](https://github.com/slack-samples/deno-starter-template/blob/b520f01e6dbfcd7cbfaf3d32b80bea9e7baada47/functions/sample_function.ts#L63) 👍
> docs: use provided function and client values for datastore calls
